variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG

# To create templates for new HW jobs, use "create-hw.sh"
include: '.gitlab-ci/**.yml'
