3-http:
  extends: .hw-test
  image: docker:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - apk add --no-cache go=1.18.6-r0 bash
  script:
    - cd 3-http
    - docker build ./server -t hw3img
    - cd tests
    - USE_DOCKER=true SOLUTION_HOST=docker go test
