version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        ports:
            - "15672:15672"
            - "5672:5672"
    web:
        build: 
            context: server
        volumes:
            - data-volume:/data
    worker:
        build: 
            context: worker
        volumes:
            - data-volume:/data
    pytest:
        build: tests/

volumes:
    data-volume: 