# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessenger.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n\rClientMessage\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"C\n\x13SendMessageResponse\x12,\n\x08sendTime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"[\n\rServerMessage\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12,\n\x08sendTime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x85\x01\n\tMessenger\x12\x35\n\x0bSendMessage\x12\x0e.ClientMessage\x1a\x14.SendMessageResponse\"\x00\x12\x41\n\x13GetAndFlushMessages\x12\x16.google.protobuf.Empty\x1a\x0e.ServerMessage\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messenger_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTMESSAGE._serialized_start=81
  _CLIENTMESSAGE._serialized_end=126
  _SENDMESSAGERESPONSE._serialized_start=128
  _SENDMESSAGERESPONSE._serialized_end=195
  _SERVERMESSAGE._serialized_start=197
  _SERVERMESSAGE._serialized_end=288
  _MESSENGER._serialized_start=291
  _MESSENGER._serialized_end=424
# @@protoc_insertion_point(module_scope)
